### ISSUE TITLE
Non-virtual destructor in abstract classes

### ISSUE THREAD

**Issue by alex-novinski** [tstu-alumni/code-challenge#2]
In ChemProcess app commit b0e05d835fe7bc5fc06792ff6731300446e2deba I get the warning as follows:
delete called on 'ChProcess' that is abstract but has non-virtual destructor

What does it take to get rid of the warning and what is the potential problem related to the warning?

**Comment by naccuracy** [comment]
non-virtual destructors can cause memory leaks if you try to delete object using pointer to base class. You should make destructor virtual every time you have one or more virtual functions in your class.
